# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ff1ca412975db5143e69c5542bc7f08"
application_url = "https://quick-cart-sticky-bar-production.up.railway.app"
embedded = true
name = "QuickCart Sticky Bar"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://quick-cart-sticky-bar-production.up.railway.app/api/auth" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[build]
automatically_update_urls_on_dev = true
